services:
  postgres:
    container_name: threads_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: treads

volumes:
  postgres_data:


#      - /e/ThreadsBackend-ExpressGraphQL:/var/lib/postgresql/data
