version: '3.8'

services:
  postgres:
    container_name: threads_db
    image: postgres:latest
    environment:
      POSTGRES_USER: kota
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
